resources:
  repositories:
    - repository: templates
      type: git
      name: pipeline-templates

variables:
  - group: FT Credentials - Pension - Dev
  - group: Stash Credentials

jobs:
  - template: build/functional-tests.yaml@templates
    parameters:
      environment: dev
