# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports: 
      - '5432:5432'

# to create run: docker-compose -f postgress.yaml up